### PR TITLE
setup initial static site

### PR DESCRIPTION
**Pull request by dworthen**

### CODE REVIEW

**Review by emrekiciman — APPROVED** [review]
Thanks @dworthen!  This is a great skeleton for the site.  I expect we'll have lots of edits and additions to come, but it looks like they'll be easy to make given this initial site.

@amit-sharma @petergtz can you take a quick look as well?

My suggestion is to merge this PR and then we start submitting new PRs to make any edits/corrections and add additional content.

Thanks,

**Comment by amit-sharma** [comment]
Thank you so much for starting this @dworthen. To give us some idea of the website, can you share a few screenshots from your local build?

**Comment by dworthen** [comment]
image
image
image
image
image
image

**Review by amit-sharma — APPROVED** [review]
thanks! The content is a bit rough but it is a good start. In the spirit of setting up a base for adding more PRs for content-specific changes, I'm happy to approve this.

That said, we'll need to work fast on the next set of PRs, since I assume that this website will be deployed and available as soon as this PR is merged.

**Comment by petergtz** [comment]
@dworthen Great stuff! Thanks for doing this. Agree with comments from @amit-sharma and @emrekiciman on getting this out and then iterating.

A few comments already:
- We need to be careful about how much this should dive into DoWhy versus staying on the PyWhy level for this website. So far, I thought this website would be mainly for PyWhy and provide links into the DoWhy documentation. If we change this approach, I guess it's also fine, we should then just decide on what should be on the website and what should be in the documentation (I consider documentation to be everything in https://py-why.github.io/dowhy. If this is an outdated view things, let me know :-) )
- How will installation instructions be separated from those in the documentation?
- We may want to update the PyWhy logo too as part of this work (not this PR). That logo was meant as a placeholder for a proper one.

**Review by petergtz — APPROVED** [review]

**Pull request merged**
