### PR TITLE
add econml v0.15 youtube video

### PR DESCRIPTION
**Pull request by fverac**
Adds the most recent pywhy talk to the videos page. 

Screenshot below
image

### CODE REVIEW

**Review by amit-sharma — APPROVED** [review]
Looks good, thanks

**Review by emrekiciman — COMMENTED** [review]
lgtm

**Comment by emrekiciman** [comment]
general question, do we have a policy on the display order of videos?

**Comment by fverac** [comment]
> general question, do we have a policy on the display order of videos?

Currently they are in just chronological order (newest at bottom) but maybe we should do it the other way (newest at top)

**Pull request merged**
